# Example Zone Configuration for Person ReID System
# 
# This file defines working zones for monitoring person presence
# Each zone has:
#   - name: Human-readable zone name
#   - polygon: List of [x, y] coordinates defining the zone boundary
#   - authorized_ids: List of Global IDs allowed in this zone
#
# Coordinates are in pixels relative to video resolution
# Example: For 1920x1080 video, x ranges from 0-1920, y from 0-1080

zones:
  # Zone 1: Assembly Area (restricted to Duong only)
  zone1:
    name: "Assembly Area"
    polygon:
      - [100, 100]    # Top-left corner
      - [400, 100]    # Top-right corner
      - [400, 300]    # Bottom-right corner
      - [100, 300]    # Bottom-left corner
    authorized_ids: [1]  # Only Duong (Global ID: 1) is authorized
  
  # Zone 2: Packaging Area (restricted to Khiem only)
  zone2:
    name: "Packaging Area"
    polygon:
      - [450, 100]
      - [750, 100]
      - [750, 300]
      - [450, 300]
    authorized_ids: [2]  # Only Khiem (Global ID: 2) is authorized
  
  # Zone 3: Common Area (both Duong and Khiem allowed)
  zone3:
    name: "Common Area"
    polygon:
      - [800, 100]
      - [1100, 100]
      - [1100, 400]
      - [800, 400]
    authorized_ids: [1, 2]  # Both Duong and Khiem authorized
  
  # Zone 4: Restricted Area (no one allowed - for testing violations)
  zone4:
    name: "Restricted Area"
    polygon:
      - [1150, 100]
      - [1400, 100]
      - [1400, 300]
      - [1150, 300]
    authorized_ids: []  # No one is authorized - all entries are violations

# Notes:
# 1. Polygon can be any shape (not just rectangles)
#    - Minimum 3 points required
#    - Points should be in clockwise or counter-clockwise order
#
# 2. Authorized IDs must match Global IDs in Qdrant database
#    - Check registered persons in "Register Person" page
#    - IDs are assigned during registration
#
# 3. Zone detection uses IOU (Intersection over Union)
#    - Default threshold: 60% overlap
#    - Adjustable in UI (30% - 90%)
#
# 4. To find coordinates for your video:
#    - Use video editing software to get pixel coordinates
#    - Or use OpenCV to click on video frame
#    - Or estimate based on video resolution
#
# Example for different video resolutions:
#
# 1920x1080 (Full HD):
#   - Top-left: [0, 0]
#   - Top-right: [1920, 0]
#   - Bottom-right: [1920, 1080]
#   - Bottom-left: [0, 1080]
#
# 1280x720 (HD):
#   - Top-left: [0, 0]
#   - Top-right: [1280, 0]
#   - Bottom-right: [1280, 720]
#   - Bottom-left: [0, 720]
#
# 640x480 (SD):
#   - Top-left: [0, 0]
#   - Top-right: [640, 0]
#   - Bottom-right: [640, 480]
#   - Bottom-left: [0, 480]

